import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent implements OnInit {
  user = {
    email: '',
    senha: ''
  };

  myLogo = 'res://logo2.png';

  constructor() {}

  ngOnInit() {}

  submit() {
    /* if (!this.user.email || !this.user.password) {
      this.alert('Por favor, preencha e-mail e senha.');
      return;
    }

    this.alert("Login efetuado com sucesso."); */

    console.log('teste');
  }
}
